apiVersion: v1
kind: Pod
metadata:
  name: getway-pod
  labels:
    app: getway
    type: microservice
spec:
  containers:
    - name: getway-app
      image: rchalco/serviciosapigateway:latest
      ports:
        - containerPort: 80