#POD for microservices library
apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  labels:
    app: microservice-seguridad
    type: microservice
spec:
  containers:
    - name: microservice-seguridad-app
      image: rchalco/serviciosapiseguridad:latest
      ports:
        - containerPort: 80
      #env:
      #  - name: ConnectionStrings__ConexionDB
      #    value: "Data Source=mssql-service; Initial Catalog=Seguridad;User Id=sa;Password=admin.123;"          