#POD for deploy libreria
apiVersion: apps/v1
kind: Deploymnent
metadata:
  name: microservice-libreria-deploy
  labels:
    name: microservice-libreria-deploy
    app: microservice
spec:
  replicas: 2
  selector:
    matchLables:
       app: microservice-libreria
       type: microservice
  template:
    metadata:
      name: microservice-libreria-pod
      labels:
        app: microservice-libreria
        type: microservice
    spec:
      containers:
        - name: microservice-libreria-app
          image: rchalco/serviciosapilibreria:latest
          ports:
            - containerPort: 80
          env:
            - name: MongoDb__ConnectionString
              value: mongodb://rchalco:admin.123@mongo-service:27017