#POD for microservices library
apiVersion: v1
kind: Pod
metadata:
  name: microservice-libreria-pod
  labels:
    app: microservice-libreria
    type: microservice
spec:
  containers:
    - name: microservice-libreria-app
      image: rchalco/serviciosapilibreria:latest
      ports:
        - containerPort: 80
      env:
        - name: MongoDb__ConnectionString
          value: mongodb://rchalco:admin.123@mongo-service:27017