#POD for microservices library
apiVersion: v1
kind: Pod
metadata:
  name: mssql-pod
  labels:
    app: microservice-seguridad
    name: mssql-pod
spec:
  containers:
    - name: mssql
      image: mcr.microsoft.com/mssql/server
      env:
      - name: ACCPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "admin.123"
      ports:
        - containerPort: 1433